### ISSUE TITLE
FEATURE request - Data driven testing

### ISSUE THREAD

**Issue by geekflyer** [bahmutov/snap-shot-it#13]
- version 2.1.0

First of all - awesome library - thanks for the great idea.

I was wondering if you could add the data-driven testing capability similar to what is already in `snap-shot` ?

**Comment by bahmutov** [comment]
That would be nice, let me think about it. It seems that is more of a 3rd party lib thing ...

**Comment by bahmutov** [comment]
https://github.com/bahmutov/snap-shot/issues/38

**Comment by bahmutov** [comment]
Version `3.2.0` has been published to NPM. The full release note can be found at [snap-shot-it/releases/tag/v3.2.0](https://github.com/bahmutov/snap-shot-it/releases/tag/v3.2.0).

**Tip:** safely upgrade dependency snap-shot-it in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by geekflyer** [comment]
thanks!

**Comment by bahmutov** [comment]
Anytime @geekflyer anytime
