### ISSUE TITLE
Snapshot env vars should be prefixed

### ISSUE THREAD

**Issue by brian-mann** [bahmutov/snap-shot-it#14]
the `UPDATE`, `SHOW`, `DRY` env vars should all be prefixed with `SNAPSHOT`

- `SNAPSHOT_UPDATE`
- `SNAPSHOT_SHOW`
- `SNAPSHOT_DRY`

As it stands it's not clear at all what these env vars would be applicable to. Too generic :P

**Comment by bahmutov** [comment]
Good point

**Comment by bahmutov** [comment]
Version `3.0.0` has been published to NPM. The full release note can be found at [snap-shot-it/releases/tag/v3.0.0](https://github.com/bahmutov/snap-shot-it/releases/tag/v3.0.0).

**Tip:** safely upgrade dependency snap-shot-it in your project using [next-update](https://github.com/bahmutov/next-update)
