### ISSUE TITLE
Add snapshot pruning

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot-it#15]
At the end of the run, check if each snapshot has a corresponding test (even if skipped). Since we do this by spec file, we only prune tests from a given file, and not accidentally going to delete snapshots from spec files not running.

**Comment by bahmutov** [comment]
Version `3.1.0` has been published to NPM. The full release note can be found at [snap-shot-it/releases/tag/v3.1.0](https://github.com/bahmutov/snap-shot-it/releases/tag/v3.1.0).

**Tip:** safely upgrade dependency snap-shot-it in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by brian-mann** [comment]
When using an `only` this ends up deleting every other snapshot.

**Comment by bahmutov** [comment]
yes, I noticed, because it does not call a callback with skipped tests. Hope that when you remove `.only` it recreates the snapshots, which should still have a short Git diff
