### ISSUE TITLE
Renaming tests wreaks havoc

### ISSUE THREAD

**Issue by brian-mann** [bahmutov/snap-shot-it#16]
After using this for awhile I have come to figure out that the ergonomics for using this could use some improvement.

For instance, having the test titles automatically populated *IS* nice, but its not great for iterations. Often I am renaming tests or reorganizing.

When this happens its *very* difficult if not impossible to manually pair up the old snapshot with the new snapshot, and it's very easy to let a failure sneak in.

Proposal: enable giving the snapshot your own `name` instead of it automatically pulling from `mocha`.

That would not only persist through test refactors, but prevent the situation where old snapshots continually get created and 'stick around' forever.

**Comment by bahmutov** [comment]
This is possible by using `snap-shot-core` directly, and could be added as a change here.
Probably something like 'if first argument is a string' and there are two arguments, then use that as a name
```js
snapshot('my custom name', value)
```

**Comment by bahmutov** [comment]
BTW, now the tests are pruned #15

**Comment by brian-mann** [comment]
Sure, that will be helpful. Setting a name seems to be the best option as that avoids the need to remove old snapshots (until the test itself is deleted) and custom names can make it through test title refactoring.

**Comment by bahmutov** [comment]
Version `3.3.0` has been published to NPM. The full release note can be found at [snap-shot-it/releases/tag/v3.3.0](https://github.com/bahmutov/snap-shot-it/releases/tag/v3.3.0).

**Tip:** safely upgrade dependency snap-shot-it in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by brian-mann** [comment]
It appears when using mocha in watch mode, and an `only` that it will continually increment the `snapshot` version... `1, 2, 3`

**Comment by bahmutov** [comment]
god damn the watch mode, I am probably not clearing the cache correctly! The worst is that I prefer not to use the watch mode myself, so I am not solving my problems here

**Comment by brian-mann** [comment]
You could just make it that if an explicit snapshot name was passed, never to increment the number (or even display the number) for that matter.

It really only makes sense when the titles are auto generated.

**Comment by bahmutov** [comment]
Let's just switch to Jest at this point - the release today has huge work going in for them
