### ISSUE TITLE
Question: Usage with Qunit?

### ISSUE THREAD

**Issue by monovertex** [bahmutov/snap-shot-it#20]
Would it be possible to use this plugin with the Qunit framework, which lacks the `it` function?

I'm looking to do snap shot testing in Ember, which uses Qunit. Ember can also switch to Mocha, but I'd like to avoid migrating all the tests, if possible.

Thanks!

**Comment by bahmutov** [comment]
Hi!

Good question. I wrote a few plugins for QUnit, but now do not remember if inside a "beforeEach" QUnit gives you the current test. I see two things you can do
- fork this project and maybe use `snap-shot-core` to write something that is a plugin for QUnit
- look at https://github.com/bahmutov/snap-shot project - that project does NOT rely on `beforeEach` hook, so it might work for QUnit. Hmm, I even have my open issue there https://github.com/bahmutov/snap-shot/issues/60

**Comment by monovertex** [comment]
Thanks! I'll check out how snap-shot-core works and probably try to wrap it for QUnit.

As for the snap-shot project, I did see it and the issue, but we're transpiling ES8 code, so I doubt that project is going to help me.

I'll let you know if I come up with a viable integration solution.

PS: Yes, `beforeEach` does have access to the test context.

**Comment by monovertex** [comment]
We no longer require this for that specific use case.
