### ISSUE TITLE
Possible test coverage implementation

### ISSUE THREAD

**Issue by mcguiretj** [bahmutov/snap-shot-it#22]
Have test coverage to illustrate how much of your app is covered?

<a href="https://facebook.github.io/jest/docs/en/cli.html#coverage">Jest Test Coverage</a>
<a href="https://www.google.com/search?q=jest+test+coverage&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiggvGYlMHWAhXB7CYKHat9BugQ_AUIDCgD&biw=1280&bih=708">Google Images</a>

**Comment by bahmutov** [comment]
But we are talking snapshots of data - not of code. So other tools like `istanbul`, `nyc` should be the solution, not the snapshots. I can only recommend looking and thinking how to compute *data coverage* of your tests https://glebbahmutov.com/blog/data-coverage/

**Comment by mcguiretj** [comment]
Ah I see, gotcha. I didn't know about the information with the link you just sent. I will read and learn more about data coverage. Thanks!
