### ISSUE TITLE
Different destination folder for the snapshots

### ISSUE THREAD

**Issue by ematipico** [bahmutov/snap-shot-it#26]
## Is this a bug report or a feature request?
Feature request 

I wonder if would be possible to have an option somewhere (maybe `package.json`?) where it tells `snap-shot-it` to create the `__snapshopts__` folder inside the same folder level of the spec file?

-> foo
--> foo.js
--> foo.test.js
--> __snapshots__
---> foo.test.js

**Comment by bahmutov** [comment]
It is good feature- if you do a pull request we can merge it

**Comment by ematipico** [comment]
I can do a PR, do you have any hint? I looked at the code and it looks like I have to do a PR against the [snap-shot-core](https://github.com/bahmutov/snap-shot-core), right?

Do you want to have an optional option to pass as node env variable? So it won't break existing functionality
