### ISSUE TITLE
Switch + and - for diffs

### ISSUE THREAD

**Issue by Bkucera** [bahmutov/snap-shot-it#98]
### enhancement

I've been tripped up a few times because I mix up whether `+` and `-` is referring to the snapshot value in the file, or the new incoming one from the test. Since the majority of use case is fixing a broken test, I think the `+` and `-` should be in reference to the `incoming` snapshot. `+` meaning the incoming snapshot has some new line, `-` meaning the incoming snapshot is missing a line.

Current behavior is below, my incoming snapshot is `[no output]`. I would prefer the `+` to be next to `[no output]`
![image](https://user-images.githubusercontent.com/14625260/40859612-64da78fc-65b0-11e8-92b6-a9aa62303aed.png)

Any thoughts on this?

**Comment by bahmutov** [comment]
so we do want something like this (with extra information I think)

<img width="1390" alt="screen shot 2018-06-01 at 4 14 22 pm" src="https://user-images.githubusercontent.com/2212006/40861402-f1769ad8-65b6-11e8-8b28-935a244ed34b.png">

but the actual comparison and message are done in another module I think, you would need to trace it

**Comment by bahmutov** [comment]
ok, I think this is all resolved in v7.4.2 https://github.com/bahmutov/snap-shot-it/releases/tag/v7.4.2 @Bkucera
